stages:
  - build
  - release

before_script:
  - mkdir -p _ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/_ccache

cache:
  paths:
    - _ccache/

build-main:
  image: archlinux/base
  stage: build
  script:
   - pacman -Sy
   - pacman -S --noconfirm libwnck3 gtk3 vala meson git base-devel clang ninja
   - meson build --prefix=/usr && cd build
   - ninja
   - ninja install
   - ninja dist
  artifacts:
    paths:
    - "build/vala-panel*.tar.xz"
    expire_in: 1 week


release-main:
  image: archlinux/base
  stage: release
  script:
    - pacman -Sy
    - pacman -S --noconfirm python3 python-pip
    - pip3 install gitlab_release
    - python3 -m gitlab_release ${PRIVATE_TOKEN} build/vala-panel*.tar.xz
  only:
    - tags
