image: pritunl/archlinux
stages:
  - build
before_script:
  - mkdir -p _ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/_ccache
  - pacman -S --noconfirm libwnck3 gtk3 vala cmake git base-devel clang ninja
  - git clone https://gitlab.com/vala-panel-project/cmake-vala.git
  - cd cmake-vala && cmake . -DCMAKE_INSTALL_PREFIX=/usr -GNinja && ninja install && cd ..
cache:
  paths:
    - _ccache/
build:
  stage: build
  script:
   - cmake . -DCMAKE_INSTALL_PREFIX=/usr -GNinja
   - ninja
   - ninja install
   - ninja dist
  artifacts:
    paths:
    - "vala-panel*.tar.xz"
    expire_in: 1 week
